# Nome da Aplicação
spring.application.name=agencia-viagens-api

# Porta onde o servidor vai rodar (Padrão: 8080)
server.port=8080

# Configurações do Swagger / OpenAPI
# Define a URL amigável para acessar a documentação interativa
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Formatação de saída JSON no console/respostas (opcional, para legibilidade)
spring.jackson.serialization.indent_output=true

# =========================================================
# Configurações do Banco de Dados PostgreSQL e Hibernate
# =========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/viagens_db
spring.datasource.username=postgres
spring.datasource.password=210397
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin123