# Nome da Aplicação
spring.application.name=agencia-viagens-api

# Porta onde o servidor vai rodar (Padrão: 8080)
server.port=8080

# Configurações do Swagger / OpenAPI
# Define a URL amigável para acessar a documentação interativa
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Formatação de saída JSON no console/respostas (opcional, para legibilidade)
spring.jackson.serialization.indent_output=true